import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The OpenAPI plugin generates docs/api/reference/sidebar.ts at sync time
// (`npm run sync:openapi`). The file is gitignored — on a fresh clone it
// won't exist until sync runs. Try/catch so plain `npm start` after clone
// renders the rest of the site with just the /api landing.
let apiReferenceItems: SidebarsConfig['docs'] = [];
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const apiSidebar = require('./docs/api/reference/sidebar');
  const exported = apiSidebar.default ?? apiSidebar;
  apiReferenceItems = exported.apisidebar ?? [];
} catch {
  // sidebar.ts not generated yet — run `npm run sync:openapi`
  apiReferenceItems = [];
}

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      link: {type: 'doc', id: 'getting-started/index'},
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Architecture',
      link: {type: 'doc', id: 'architecture/index'},
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
    {
      type: 'category',
      label: 'Operating Orkestra',
      link: {type: 'doc', id: 'operating/index'},
      items: [{type: 'autogenerated', dirName: 'operating'}],
    },
    {
      type: 'category',
      label: 'Module Catalog',
      link: {type: 'doc', id: 'modules/index'},
      items: [{type: 'autogenerated', dirName: 'modules'}],
    },
    {
      type: 'category',
      label: 'SDK',
      link: {type: 'doc', id: 'sdk/index'},
      items: [{type: 'autogenerated', dirName: 'sdk'}],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'api/index'},
      items: apiReferenceItems,
    },
    {
      type: 'category',
      label: 'ADRs',
      link: {type: 'doc', id: 'adrs/index'},
      items: [{type: 'autogenerated', dirName: 'adrs'}],
    },
    {
      type: 'category',
      label: 'Contributing',
      link: {type: 'doc', id: 'contributing/index'},
      items: [{type: 'autogenerated', dirName: 'contributing'}],
    },
  ],
};

export default sidebars;
