#!/usr/bin/env tsx
/**
 * Sync the canonical OpenAPI spec from the monorepo into static/openapi/.
 *
 * Source: orkestra-cc/orkestra @ main → backend/openapi/enterprise.json
 *         (regenerated by `make openapi-dump` in the monorepo; gated by
 *          `make openapi-check` in ci-backend)
 *
 * Output: static/openapi/enterprise.json
 *
 * The docusaurus-plugin-openapi-docs `gen-api-docs` step then converts this
 * file into per-endpoint MDX under docs/api/reference/. Both are gitignored.
 *
 * Run locally:  npm run sync:openapi
 * Run in CI:    same script — see .github/workflows/build.yml and sync-nightly.yml
 */
import {writeFileSync, mkdirSync} from 'node:fs';
import {dirname, resolve, join} from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');
const OUT_DIR = join(REPO_ROOT, 'static', 'openapi');
const OUT_FILE = join(OUT_DIR, 'enterprise.json');

// Source branch — `main` is the long-term target, but until the canonical
// spec lands on `main` (it's accumulating on `dev` between batched
// dev→main promotions), we pull from `dev` so the API reference renders
// end-to-end. Override via SPEC_REF env var when piloting changes.
// Switch the default back to 'main' on the first promotion that includes
// backend/openapi/enterprise.json.
const SPEC_REF = process.env.SPEC_REF ?? 'dev';
const SPEC_URL = `https://raw.githubusercontent.com/orkestra-cc/orkestra/${SPEC_REF}/backend/openapi/enterprise.json`;

async function main() {
  mkdirSync(OUT_DIR, {recursive: true});
  console.log(`→ Fetching ${SPEC_URL}`);
  const res = await fetch(SPEC_URL);
  if (!res.ok) {
    throw new Error(`fetch ${SPEC_URL} → ${res.status} ${res.statusText}`);
  }
  const body = await res.text();
  // Sanity-check it parses as OpenAPI 3 before writing.
  const parsed = JSON.parse(body);
  if (typeof parsed?.openapi !== 'string' || !parsed.openapi.startsWith('3.')) {
    throw new Error(`fetched spec is not OpenAPI 3.x (got openapi=${parsed?.openapi ?? '<missing>'})`);
  }
  const paths = Object.keys(parsed.paths ?? {}).length;
  writeFileSync(OUT_FILE, body);
  console.log(`✓ Wrote ${OUT_FILE} (${body.length} bytes, ${paths} paths, openapi ${parsed.openapi})`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
